version: "3.8"

services:
  nginx:
    depends_on:
      - api
      - client
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "${REVERSE_PROXY_PORT}:80"
  client:
    environment:
      - WDS_SOCKET_PORT=0
    expose:
      - ${REACT_APP_PORT}
      # - CHOKIDAR_USEPOLLING=true # For windows wsl support
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    # stdin_open: true # True to Keep container open to allow for debugging
    # tty: true # True to Keep container open to allow for debugging
  api:
    # environment:
    #   - CHOKIDAR_USEPOLLING=true # For windows wsl support
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - PORT=${API_PORT}
      - MONGODB_URI=mongodb://db:27017/inventory
      - DOCKER=true
      - SECRET=${SECRET}
    expose:
      - ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    # volumes:
    #   - ./api:/usr/src/app
    #   - /usr/src/app/node_modules
  db:
    image: mongo
    container_name: db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    environment:
      - PUID=1000
      - PGID=1000
